# Generated by Django 6.0 on 2025-12-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Verfügbar'), ('unavailable', 'Nicht verfügbar'), ('maybe', 'Vielleicht'), ('pending', 'Offen')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Verfügbarkeit',
                'verbose_name_plural': 'Verfügbarkeiten',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Geburtsdatum')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('mobile', models.CharField(blank=True, max_length=50, verbose_name='Mobil')),
                ('member_number', models.CharField(blank=True, max_length=50, verbose_name='Mitgliedsnummer')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='Eintrittsdatum')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('inactive', 'Inaktiv'), ('youth', 'Jugendfeuerwehr'), ('honorary', 'Alters- und Ehrenabteilung'), ('reserve', 'Reserve')], default='active', max_length=20, verbose_name='Status')),
                ('preferred_positions', models.TextField(blank=True, help_text='Kommaseparierte Liste bevorzugter Positionen', verbose_name='Wunschpositionen')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Mitglied',
                'verbose_name_plural': 'Mitglieder',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('short_name', models.CharField(blank=True, max_length=20, verbose_name='Kurzname')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Einheit',
                'verbose_name_plural': 'Einheiten',
                'ordering': ['order', 'name'],
            },
        ),
    ]
