# Generated by Django 6.0 on 2025-12-14 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qualifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('short_name', models.CharField(max_length=20, unique=True, verbose_name='Kurzname')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positionen',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sign', models.CharField(help_text='z.B. 05-HLF20-01', max_length=50, unique=True, verbose_name='Funkrufname')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Bezeichnung')),
                ('license_plate', models.CharField(blank=True, max_length=20, verbose_name='Kennzeichen')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Niedrigere Werte = höhere Priorität bei der Besetzung', verbose_name='Besetzungspriorität')),
                ('has_optional_messenger', models.BooleanField(default=False, help_text='Für historische Daten oder spätere Erweiterung', verbose_name='Hat optionalen Melderplatz')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
            ],
            options={
                'verbose_name': 'Fahrzeug',
                'verbose_name_plural': 'Fahrzeuge',
                'ordering': ['priority', 'call_sign'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('short_name', models.CharField(max_length=20, unique=True, verbose_name='Kurzname')),
                ('crew_size', models.CharField(help_text='z.B. 1/8, 1/5, 1/2', max_length=20, verbose_name='Besatzungsstärke')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge/Priorität')),
            ],
            options={
                'verbose_name': 'Fahrzeugtyp',
                'verbose_name_plural': 'Fahrzeugtypen',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehiclePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField(default=1, help_text='Für die Reihenfolge auf dem Fahrzeug', verbose_name='Sitzplatznummer')),
                ('is_required', models.BooleanField(default=True, help_text='Muss diese Position besetzt sein?', verbose_name='Pflichtposition')),
                ('is_optional', models.BooleanField(default=False, help_text='z.B. Melderplatz', verbose_name='Optional')),
                ('requires_agt', models.BooleanField(default=False, help_text='Muss gültigen Atemschutz-Status haben', verbose_name='Erfordert AGT-Status')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_positions', to='vehicles.position', verbose_name='Position')),
                ('preferred_qualifications', models.ManyToManyField(blank=True, related_name='preferred_for_positions', to='qualifications.qualification', verbose_name='Bevorzugte Qualifikationen')),
                ('required_qualifications', models.ManyToManyField(blank=True, related_name='required_for_positions', to='qualifications.qualification', verbose_name='Pflichtqualifikationen')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='vehicles.vehicle', verbose_name='Fahrzeug')),
            ],
            options={
                'verbose_name': 'Fahrzeug-Position',
                'verbose_name_plural': 'Fahrzeug-Positionen',
                'ordering': ['vehicle', 'seat_number'],
                'unique_together': {('vehicle', 'position')},
            },
        ),
        migrations.CreateModel(
            name='PositionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('required', 'Erforderlich'), ('preferred', 'Bevorzugt'), ('allowed', 'Erlaubt (mit Warnung)')], default='required', max_length=20, verbose_name='Regeltyp')),
                ('description', models.CharField(max_length=255, verbose_name='Beschreibung')),
                ('all_required', models.BooleanField(default=False, help_text='Alle Qualifikationen müssen vorhanden sein (UND) vs. eine davon (ODER)', verbose_name='Alle erforderlich')),
                ('warning_text', models.CharField(blank=True, help_text='Wird angezeigt wenn Regel verletzt wird', max_length=255, verbose_name='Warnungstext')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Priorität')),
                ('qualifications', models.ManyToManyField(related_name='position_rules', to='qualifications.qualification', verbose_name='Qualifikationen')),
                ('vehicle_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='vehicles.vehicleposition', verbose_name='Fahrzeug-Position')),
            ],
            options={
                'verbose_name': 'Positionsregel',
                'verbose_name_plural': 'Positionsregeln',
                'ordering': ['priority'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.vehicletype', verbose_name='Fahrzeugtyp'),
        ),
    ]
