# Generated by Django 6.0 on 2025-12-14 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kürzel')),
                ('name', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('validity_months', models.PositiveIntegerField(default=36, help_text='z.B. 36 Monate für G26.3', verbose_name='Gültigkeitsdauer (Monate)')),
            ],
            options={
                'verbose_name': 'Untersuchungstyp',
                'verbose_name_plural': 'Untersuchungstypen',
            },
        ),
        migrations.CreateModel(
            name='QualificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Qualifikationskategorie',
                'verbose_name_plural': 'Qualifikationskategorien',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(verbose_name='Untersuchungsdatum')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Gültig bis')),
                ('result_positive', models.BooleanField(default=True, verbose_name='Bestanden')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_exams', to='members.member', verbose_name='Mitglied')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='qualifications.medicalexamtype', verbose_name='Untersuchungstyp')),
            ],
            options={
                'verbose_name': 'Ärztliche Untersuchung',
                'verbose_name_plural': 'Ärztliche Untersuchungen',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kürzel')),
                ('name', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('requires_renewal', models.BooleanField(default=False, verbose_name='Erfordert Erneuerung')),
                ('renewal_months', models.PositiveIntegerField(blank=True, help_text='Für zeitlich begrenzte Qualifikationen wie G26.3', null=True, verbose_name='Gültigkeitsdauer (Monate)')),
                ('requires_exercises', models.BooleanField(default=False, verbose_name='Erfordert Übungen')),
                ('exercise_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Anzahl Übungen pro Jahr')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('covers', models.ManyToManyField(blank=True, related_name='covered_by', to='qualifications.qualification', verbose_name='Deckt ab')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualifications', to='qualifications.qualificationcategory', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Qualifikation',
                'verbose_name_plural': 'Qualifikationen',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='medicalexamtype',
            name='related_qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_exams', to='qualifications.qualification', verbose_name='Benötigt für Qualifikation'),
        ),
        migrations.CreateModel(
            name='ExerciseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_date', models.DateField(verbose_name='Übungsdatum')),
                ('exercise_type', models.CharField(max_length=100, verbose_name='Übungsart')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_records', to='members.member', verbose_name='Mitglied')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_records', to='qualifications.qualification', verbose_name='Für Qualifikation')),
            ],
            options={
                'verbose_name': 'Übungsnachweis',
                'verbose_name_plural': 'Übungsnachweise',
                'ordering': ['-exercise_date'],
            },
        ),
        migrations.CreateModel(
            name='MemberQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_date', models.DateField(blank=True, null=True, verbose_name='Erworben am')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='members.member', verbose_name='Mitglied')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_qualifications', to='qualifications.qualification', verbose_name='Qualifikation')),
            ],
            options={
                'verbose_name': 'Mitglieder-Qualifikation',
                'verbose_name_plural': 'Mitglieder-Qualifikationen',
                'unique_together': {('member', 'qualification')},
            },
        ),
    ]
