# Generated by Django 6.0 on 2025-12-14 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Bezeichnung')),
                ('color', models.CharField(default='#3B82F6', help_text='Hex-Farbcode für Kalenderansicht', max_length=7, verbose_name='Farbe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Diensttyp',
                'verbose_name_plural': 'Diensttypen',
            },
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('date', models.DateField(verbose_name='Datum')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Beginn')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Ende')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ort')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('planned', 'Geplant'), ('confirmed', 'Bestätigt'), ('completed', 'Abgeschlossen'), ('cancelled', 'Abgesagt')], default='draft', max_length=20, verbose_name='Status')),
                ('min_agt_count', models.PositiveIntegerField(default=0, help_text='Mindestens so viele Personen mit gültigem AGT-Status', verbose_name='Mindestanzahl AGT')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_duties', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('vehicles', models.ManyToManyField(blank=True, related_name='duties', to='vehicles.vehicle', verbose_name='Fahrzeuge')),
                ('duty_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duties', to='scheduling.dutytype', verbose_name='Diensttyp')),
            ],
            options={
                'verbose_name': 'Dienst',
                'verbose_name_plural': 'Dienste',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('suggested', 'Vorgeschlagen'), ('confirmed', 'Bestätigt'), ('locked', 'Gesperrt'), ('cancelled', 'Ausgefallen')], default='suggested', max_length=20, verbose_name='Status')),
                ('qualification_override', models.BooleanField(default=False, verbose_name='Qualifikation übersteuert')),
                ('override_reason', models.TextField(blank=True, verbose_name='Begründung für Übersteuerung')),
                ('overridden_at', models.DateTimeField(blank=True, null=True, verbose_name='Übersteuert am')),
                ('has_warning', models.BooleanField(default=False, verbose_name='Hat Warnung')),
                ('warning_text', models.TextField(blank=True, verbose_name='Warnungstext')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='members.member', verbose_name='Mitglied')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualification_overrides', to=settings.AUTH_USER_MODEL, verbose_name='Übersteuert von')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='vehicles.vehicle', verbose_name='Fahrzeug')),
                ('vehicle_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='vehicles.vehicleposition', verbose_name='Position')),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scheduling.duty', verbose_name='Dienst')),
            ],
            options={
                'verbose_name': 'Einteilung',
                'verbose_name_plural': 'Einteilungen',
                'ordering': ['duty', 'vehicle', 'vehicle_position__seat_number'],
                'unique_together': {('duty', 'vehicle_position')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('year', models.PositiveIntegerField(verbose_name='Jahr')),
                ('month', models.PositiveIntegerField(verbose_name='Monat')),
                ('qualification_valid', models.BooleanField(default=True, verbose_name='Qualifikation erfüllt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='members.member', verbose_name='Mitglied')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_history', to='vehicles.position', verbose_name='Position')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_history', to='vehicles.vehicle', verbose_name='Fahrzeug')),
                ('duty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='scheduling.duty', verbose_name='Dienst')),
                ('duty_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_history', to='scheduling.dutytype', verbose_name='Diensttyp')),
            ],
            options={
                'verbose_name': 'Einteilungs-Historie',
                'verbose_name_plural': 'Einteilungs-Historien',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['member', 'year'], name='scheduling__member__ba0eac_idx'), models.Index(fields=['vehicle', 'year'], name='scheduling__vehicle_b29690_idx'), models.Index(fields=['position', 'year'], name='scheduling__positio_2a92e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='FairnessScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Jahr')),
                ('total_duties', models.PositiveIntegerField(default=0, verbose_name='Gesamtdienste')),
                ('total_by_vehicle', models.JSONField(default=dict, help_text='{"HLF": 5, "LF": 3, "MZF": 2}', verbose_name='Dienste pro Fahrzeug')),
                ('total_by_position', models.JSONField(default=dict, help_text='{"GF": 2, "MA": 3, "ATF": 5}', verbose_name='Dienste pro Position')),
                ('last_duty_date', models.DateField(blank=True, null=True, verbose_name='Letzter Dienst')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fairness_scores', to='members.member', verbose_name='Mitglied')),
            ],
            options={
                'verbose_name': 'Fairness-Score',
                'verbose_name_plural': 'Fairness-Scores',
                'ordering': ['-year', 'member'],
                'unique_together': {('member', 'year')},
            },
        ),
    ]
