# Generated by Django 6.0 on 2025-12-15 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False, verbose_name='Anwesend')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Eingecheckt um')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_check_ins', to=settings.AUTH_USER_MODEL, verbose_name='Eingecheckt von')),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='scheduling.duty', verbose_name='Dienst')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_attendances', to='members.member', verbose_name='Mitglied')),
            ],
            options={
                'verbose_name': 'Anwesenheit',
                'verbose_name_plural': 'Anwesenheiten',
                'ordering': ['member__last_name', 'member__first_name'],
                'unique_together': {('duty', 'member')},
            },
        ),
    ]
